### ISSUE TITLE
Non-generic Slack instance information included in firmware_password_manager.py script

### ISSUE THREAD

**Issue by rtrouton** [univ-of-utah-marriott-library-apple/firmware_password_manager#1]
It appears that some non-generic Slack information was committed as part of this script:

https://github.com/univ-of-utah-marriott-library-apple/firmware_password_manager/blob/master/firmware_password_manager.py#L109-L112

**Comment by lazymutt** [comment]
How embarrassing. Thank you very much for pointing this out!!!
