### ISSUE TITLE
Slack messages

### ISSUE THREAD

**Issue by Nesteph** [univ-of-utah-marriott-library-apple/firmware_password_manager#2]
Instead of posting the IP address of the machine to slack channels, can this post the Computer Name and the IP address? This would make tracking problems in environments with dynamic IP assignments easier.

I know the code in bash that could be used to get the name is one of the following:
`scutil --get ComputerName`
`scutil --get HostName`
`scutil --get LocalHostName`

**Comment by lazymutt** [comment]
This is a great suggestion! I have a couple ideas for making the slack identifier more flexible. I'll have a new release soon.

**Comment by Nesteph** [comment]
I did notice that we had a few that reported the serial number instead of
the IP when I ran 2.1 today. That gives a pretty concrete reference to the
machine ID and isn't as volatile as the computer names are.

On Monday, March 14, 2016, Todd McDaniel notifications@github.com wrote:

> This is a great suggestion! I have a couple ideas for making the slack
> identifier more flexible. I'll have a new release soon.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/univ-of-utah-marriott-library-apple/firmware_password_manager/issues/2#issuecomment-196539351
> .

## 

Steve McMillin

**Comment by lazymutt** [comment]
I have implemented your request in our internal version. If testing goes well tonight, I'll have 2.1.1 out very soon.
