### ISSUE TITLE
srm is not available on 10.12 and later

### ISSUE THREAD

**Issue by jwrn3** [univ-of-utah-marriott-library-apple/firmware_password_manager#3]
As srm is not installed by default on 10.12 and later deleting the keyfile always fails unless --testmode is used. Perhaps /bin/rm -P could be used as an alternative?

**Comment by lazymutt** [comment]
Thank you for bringing this to my attention! I've started working on a patch and it will be available soon.

**Comment by lazymutt** [comment]
Corrected in 2.1.4.

**Comment by jwrn3** [comment]
Excellent. Thanks for the quick update.
