### ISSUE TITLE
TypeError if hash does not exist

### ISSUE THREAD

**Issue by jwrn3** [univ-of-utah-marriott-library-apple/firmware_password_manager#6]
When testing on a Mac without a hash set I got the following:

nvram: Error getting variable - 'fwpw-hash': (iokit/common) data was not found
Traceback (most recent call last):
  File "/usr/local/bin/firmware_password_manager.py", line 690, in <module>
    main()
  File "/usr/local/bin/firmware_password_manager.py", line 316, in main
    logger.warning("nvram failed on " + this_exception + " (value probably doesn't exist).")
TypeError: cannot concatenate 'str' and 'CalledProcessError' objects

A simple change to line 316 as follows fixed it:

logger.warning("nvram failed on " + str(this_exception) + " (value probably doesn't exist).")

James

**Comment by lazymutt** [comment]
**Thanks** for identifying this bug and suggesting the fix!

**Comment by jwrn3** [comment]
> On 7 Feb 2018, at 18:22, Todd McDaniel <notifications@github.com> wrote:
> 
> Thanks for identifying this bug and suggesting the fix!
> 
You're very welcome! It's a great tool and very useful so I'm happy to contribute, even in a very small way.

Best wishes,

James

--
James Nairn
Apple Support, University Information Services, University of Cambridge
http://www.uis.cam.ac.uk/about-us
mailto:mac-support@uis.cam.ac.uk
